[master]
master-01 ansible_host=192.168.1.150

[nodes]
node-01   ansible_host=192.168.1.160
node-02   ansible_host=192.168.1.161

[all:vars]
ansible_python_interpreter=/usr/bin/python3.12
ansible_user=devops
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
