- name: verefying if node has joined the cluster
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Joining Kubernetes cluster 
  ansible.builtin.command: "{{ hostvars[groups['master'][0]]['kubernetes_join_command'] }}"
  no_log: true
  register: join_result
  failed_when: 
    - join_result.rc != 0 
    - "'already exists' not in join_result.stderr"
  changed_when: join_result.rc == 0
  when: not kubelet_conf.stat.exists
